# network

networks:
  donenetwork:
    name: donenetwork
    driver: bridge

services:
  frontend:
    build: ./frontend
    container_name: frontend
    image: frontend
    restart: always
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - donenetwork
    ports:
      - 5173:5173

  backend:
    build: ./backend
    container_name: backend
    image: backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/vendor
    depends_on:
      - frontend
    ports:
      - 8000:8000
    networks:
      - donenetwork